<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5NrEQ59\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5NrEQ59/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5NrEQ59.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5NrEQ59\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5NrEQ59\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5NrEQ59',
    'container.build_id' => 'fc50fda0',
    'container.build_time' => 1645613935,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5NrEQ59');
